### ISSUE TITLE
Maintain a list of known assets and conversions to/from them.

### ISSUE THREAD

**Issue by LefterisJP** [rotkehlchenio/rotkehlchen#329]
## Problem Definition

As we discussed [here](https://github.com/rotkehlchenio/rotkehlchen/pull/326#issuecomment-469166358) with @rakanalh there are problems with representation of assets in Rotkehlchen. The same asset can have a different name in one exchange, a different name in another and even a different one in cryptocompare, coingecko or other price querying assets.

### Create asset dataclass
Maintain a list of all known assets along with some properties like when they started, if they are active e.t.c.:

```json
[
    "ADA": {"name": "Cardano", "type": "own chain", "started": 1506816000},
    "EUR": {"name": "Euro", "type": "fiat", "started": 915148800},
    "CAD": {"name": "Canadian Dollar", "type": "fiat"},
...
]
```

Create a dataclass that represent an Asset. This should look something like that:

```python
@dataclass
class Asset():
    name: str

    def canonical() -> str:
        return name

    def to_exchange(exchange_name: str) -> str:
        ...
        ...

     def to_cryptocompare() -> str:
         ....
         ....
```

Something like the above and use this wherever `asset: str` is used right now in the code and then on each exchange, price querying website e.t.c use the appropriate `to_xxx` function. And for the DB use `to_canonical()`. And everything in rotkehlchen should be in the canonical form.

The difficulty of implementation here is to actually implement all these to_xxx functions for all assets. There are a lot of them!

### Warn user for all other assets

If the user somehow gets a different asset not on the canonical list, ignore it and warn the user that this asset is not known.

### Perform a DB upgrade

Go through all the assets in the DB and if an asset is not in the canonical list, try to see if we can find where it came from. E.g. if it's an alias. If we can find turn it into the canonical form.

If not then we should keep it in the DB but let the user know that we could not determine which asset it corresponds to, data is incosistent and that user action is required. That he should also file an issue with the repository here.

Some names that should definitely be upgraded in rotkehlchen are:

1. BCHSV -> BSV
    Bitcoin satoshi's vision is known as BSV both in cryptocompare and coinmarketcap and kraken. So the canonical name should be BSV.
    https://coinmarketcap.com/currencies/bitcoin-sv/
    https://www.cryptocompare.com/coins/bsv/overview

Some names that if found in the DB will definitely need user action, since they are ambiguous:

1. AIR and AIR-2 .. and all the other multiple named tokens

### Add some checks before cryptocompare price queries

During the asset list generation noticed that some assets (mostly inactive ones)  are not in cryptocompare. Make sure to disallow price queries for these assets then. Got a TODO in the code but adding it also here as a reminder.

### Remove all caches once the DB version is upgraded

Since some caches may have changed format remove them all when rotkehlchen upgrades to the DB version that will be set after this issue is fully addressed.

**Comment by rakanalh** [comment]
> Maintain a list of all known assets along with some properties like when they started, if they are active e.t.c.:

I realize some information can be queried about current cryptocurrencies... but where do you think we can gather the information about the currency's "date started" and "type"? i am not sure exchanges provide these information... but i would have to double check.

```
def to_exchange(exchange_name: str) -> str:
        ...
        ...
```
So going with this approach would have us do `if exchange_name == 'xyz'` and then based on each asset, we would query the exchange for the "current" symbol of this asset. The first suggestion that came to mind is to have this as an exchange method not an asset method. Something like: `binance.symbol_from_asset(asset)`. 

But thinking about this also in relation to what needs to be done for cryptocompare... i think it's best to keep the dataclass clean of these differences and use another class `AssetResolver` for instance, where queries can be made there.
```
class AssetResolver:
    @staticmethod
    def to_exchange_symbol(asset: Asset, exchange: Exchange, timestamp: Timestamp):
          if asset.name == 'XRB' and timestamp < 123:
             return 'XRB'
          return exchange.get_symbol(asset)

    @staticmethod
    def to_cryptocompare(self, asset: Asset, timestamp: Timestamp):
          # CC logic here
```

> If the user somehow gets a different asset not on the canonical list, ignore it and warn the user that this asset is not known.

IMO, Rotkehlchen should record "unknown" symbols and show "not found" errors so that those can be provided to the UI where the user can visually see the list. Otherwise, logging the error would go unnoticed in some cases and might result in generating bad reports / balances.

**Comment by LefterisJP** [comment]
@rakanalh 

> I realize some information can be queried about current cryptocurrencies... but where do you think we can gather the information about the currency's "date started" and "type"? i am not sure exchanges provide these information... but i would have to double check.

Research. Find the token issuance dates, first ERC20 transaction or timestamp of first block. This is essentially the hardest part of the work.

> But thinking about this also in relation to what needs to be done for cryptocompare... i think it's best to keep the dataclass clean of these differences and use another class AssetResolver for instance, where queries can be made there.

Why not having them in the dataclass itself? What's the difference? I actually already started some implementing and I do have a singleton class much like the `AssetResolver` you posted there, but for the moment only for the loading of the known assets json data and checking if a given symbol is known.

I like the name you wrote. `AssetResolver` is better than the name I had.

> def to_exchange_symbol(asset: Asset, exchange: Exchange, timestamp: Timestamp):

The exchange object definitely does not need to be passed around. Only a mapping exists for exchanges that may have assets which are not the same as Rotkehlchen's canonical form. It's a static mapping that is not queried per exchange each time so it should be hard coded. Which is why I do not think the exchange classes need be involved here.

> IMO, Rotkehlchen should record "unknown" symbols and show "not found" errors so that those can be provided to the UI where the user can visually see the list. Otherwise, logging the error would go unnoticed in some cases and might result in generating bad reports / balances.

Definitely. That is exactly what I meant when I said to warn the user. Not just log a warning.

Also @rakanalh what do you think of the DB upgrade here? You agree it would be needed?

**Comment by rakanalh** [comment]
> Research. Find the token issuance dates, first ERC20 transaction or timestamp of first block. This is essentially the hardest part of the work.

There must be a better way than do it for more than 1500 tokens :cry: 

As for the dataclass vs `AssetResolver`, my idea was to prevent the asset from being involved with exchange / CC related functionalities... but if you think the exchange call is not needed there then go for it, this was merely a suggestion.

About the upgrades:
> If not then we have three choices. Ignore it, remove the entry or abort the upgrade with a relevant message.

This is tricky IMO:
- On one hand we can "store" the error, ignore the asset and move on. The visual feedback should let the user that things aren't very precise due to this asset being unknown. But at least the app will work with some inaccuracy that the user might want to tolerate until the issue is fixed. I see this as a good compromise.
- On the other hand, aborting the upgrade will have users either quit Rotkehlchen altogether and look for alternatives or spend some time to create an issue.
- Generally, i think the asset should **never** be removed from the DB... the user or the app should correct the mistake if it can be done.

**Comment by LefterisJP** [comment]
> There must be a better way than do it for more than 1500 tokens cry

Automating for the ERC20 tokens should be easy since we also got the addresses (I already have a list of them). But for the own blockchain tokens it will be time consuming. 

I am going to try and see if using coinpaprika's API to fill in the gaps and keep the list properly populated can work. They seem to have some of the info I wanted.

Example [here](https://api.coinpaprika.com/#tag/Coins/paths/~1coins/get)

But manual adjustments and checks will most probably be needed. Token data is just really dynamic.

> On one hand we can "store" the error, ignore the asset and move on. The visual feedback should let the user that things aren't very precise due to this asset being unknown. But at least the app will work with some inaccuracy that the user might want to tolerate until the issue is fixed. I see this as a good compromise.

This is a good point. Especially considering your second point on the fact that exiting and asking the users to file an issue could drive them away from the app. Thanks for this,

**Comment by LefterisJP** [comment]
Talking about manual adjustments. For example I had found the proper `started` timestamp for the itcoin Satoshi's vision fork (BSV) but coin paprika has it as null: https://api.coinpaprika.com/v1/coins/bsv-bitcoin-sv

**Comment by LefterisJP** [comment]
This has been finished with a lot of changes mainly in #342 but also PRs after it.
