### ISSUE TITLE
darwin-x64 install problems. 

### ISSUE THREAD

**Issue by GratefulDave** [rotkehlchenio/rotkehlchen#382]
## Problem Definition

I am using MacOS 10.14.5. 32g. Python 3.7.1. On launch of the darwin-x64, I get `The python backend crashed'. When I did get it to work briefly, I got a `Heartbeat Bleed` error.  

Under ~/Library/logs I see an empty Rotkehlchen folder. Under system.log I see:
```Jun 21 11:08:29 Davids-MacBook-Pro com.apple.xpc.launchd[1] (com.apple.xpc.launchd.oneshot.0x1000003f.rotkehlchen[96289]): Service exited due to SIGKILL | sent by CoreServicesUIAgent[96082]
Jun 21 11:13:13 Davids-MacBook-Pro com.apple.xpc.launchd[1] (com.apple.xpc.launchd.oneshot.0x10000040.rotkehlchen[96320]): Service exited due to SIGKILL | sent by CoreServicesUIAgent[96316]
Jun 21 11:13:32 Davids-MacBook-Pro com.apple.xpc.launchd[1] (com.apple.xpc.launchd.oneshot.0x10000041.rotkehlchen[96324]): Service exited due to SIGKILL | sent by CoreServicesUIAgent[96316]
Jun 21 11:14:18 Davids-MacBook-Pro com.apple.xpc.launchd[1] (com.apple.xpc.launchd.oneshot.0x10000042.rotkehlchen[96327]): Service exited due to SIGKILL | sent by CoreServicesUIAgent[96316]
```

### System Description

Here add a detailed description of your system, e.g. output of the following script:

```
Darwin Davids-MacBook-Pro.local 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64
/usr/local/bin/geth
Geth
Version: 1.8.27-stable
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.12.4
Operating System: darwin
GOPATH=
GOROOT=/usr/local/Cellar/go/1.12.4/libexec
750f5e32474ee23a423376203e671cab9841c67a
```

**Comment by LefterisJP** [comment]
Hello Dave, 
Okay so this is a similar problem to https://github.com/rotkehlchenio/rotkehlchen/issues/339
but you are using also latest OSX.

How exactly do you run rotkehlchen? I guess you download v0.6.0 and unzip it? Then what do you do? Exactly?

 I think one pain point is that you need to navigate to the executable it from the terminal as double clicking the app does not work in OSX.

**Comment by GratefulDave** [comment]
Hi Lefteris,

I got it to work. It would be great to add Coinbase (Pro), Gemini and Ledger Nano/X.

David

**Comment by LefterisJP** [comment]
That's good to hear! Then I am closing the issue. There is an issue for Coinbase: https://github.com/rotkehlchenio/rotkehlchen/issues/296

But nothing yet for Gemini or Ledger Nano/X. If you would like to see them happen in rotkehlchen please open issues as this helps me track how many people need the features.

**Comment by tschubotz** [comment]
I just experienced the same issue:
1. I downloaded 0.6.0 from Github
2. I unzipped the file.
3. I opened `rotkehlchen.app` with a right-click -> `open` to make MacOS allow me to open the file due to `Unidentified developer`
4. I got a popup with `The Python backend crashed`
5. App closes after closing the popup.
7. I hit `CMD+o` to open the app again (Which now works even with the `Unidentified developer` issue since I manually allowed this before.)
8. No `The Python backend crashed`
9. I try to create a new account
10. After confirming my user details, there is a spinner.
11. After 30s there is another popup due to a timeout saying something about `Lost heartbeat`
12. After closing the popup, I get back to the page where I can log in or sign up, but cannot continue.

The app works like a charm when running the executable via the command line.

Hope this helps.

System info: 
`Darwin asdf 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64`

**Comment by LefterisJP** [comment]
Thank you for writting out the detailed steps of what you tried.

Yes the app should only be ran as an executable through the command line at this point in both OSX and linux. I am not very familiar with OSX and have not made it into a proper dmg. There is an open issue for [this](https://github.com/rotkehlchenio/rotkehlchen/issues/26)
